# Generated by Django 5.2.16 on 2026-07-19 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(blank=True, max_length=160, verbose_name='nome público')),
                ('professional_title', models.CharField(blank=True, max_length=180, verbose_name='título profissional')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='localização')),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos/%Y/%m/', verbose_name='fotografia')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('changes_pending', 'Alterações pendentes'), ('suspended', 'Suspenso'), ('archived', 'Arquivado'), ('deleted', 'Eliminado')], db_index=True, default='draft', max_length=24, verbose_name='estado')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='taxonomy.skill', verbose_name='competências')),
                ('specializations', models.ManyToManyField(blank=True, related_name='profiles', to='taxonomy.specialization', verbose_name='especializações')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'perfil profissional',
                'verbose_name_plural': 'perfis profissionais',
                'ordering': ('public_name', 'user__email'),
            },
        ),
    ]
