# Generated by Django 5.2.16 on 2026-07-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='privacidade aceite em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_privacy_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='versão da privacidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='termos aceites em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='versão dos termos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponível'), ('open', 'Aberto a propostas'), ('unavailable', 'Indisponível')], default='open', max_length=20, verbose_name='disponibilidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_contact',
            field=models.BooleanField(default=False, verbose_name='consentimento para contacto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_marketing',
            field=models.BooleanField(default=False, verbose_name='consentimento de marketing'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_profile_public',
            field=models.BooleanField(default=False, verbose_name='consentimento para perfil público'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_visibility',
            field=models.CharField(choices=[('form', 'Apenas formulário'), ('registered', 'Utilizadores registados'), ('public', 'Público')], default='form', max_length=20, verbose_name='visibilidade dos contactos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Guiné-Bissau', max_length=100, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='resumes/%Y/%m/', verbose_name='currículo em PDF'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='currículo atualizado em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='willing_to_relocate',
            field=models.BooleanField(default=False, verbose_name='disponível para mudança'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_preference',
            field=models.CharField(choices=[('onsite', 'Presencial'), ('remote', 'Remoto'), ('hybrid', 'Híbrido')], default='hybrid', max_length=20, verbose_name='preferência de trabalho'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='certificação')),
                ('issuer', models.CharField(max_length=180, verbose_name='entidade emissora')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='data de emissão')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='data de validade')),
                ('credential_url', models.URLField(blank=True, verbose_name='ligação da credencial')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'certificação',
                'verbose_name_plural': 'certificações',
                'ordering': ('-issue_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=180, verbose_name='instituição')),
                ('qualification', models.CharField(max_length=180, verbose_name='qualificação')),
                ('field_of_study', models.CharField(blank=True, max_length=180, verbose_name='área de estudo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'formação',
                'verbose_name_plural': 'formações',
                'ordering': ('-end_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='cargo')),
                ('organization', models.CharField(max_length=180, verbose_name='organização')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='localização')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('is_current', models.BooleanField(default=False, verbose_name='cargo atual')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'experiência profissional',
                'verbose_name_plural': 'experiências profissionais',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='idioma')),
                ('level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermédio'), ('advanced', 'Avançado'), ('fluent', 'Fluente'), ('native', 'Nativo')], max_length=20, verbose_name='nível')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_profile_language')],
            },
        ),
    ]
