# Generated by Django 5.2.16 on 2026-07-19 16:55

from uuid import uuid4

from django.db import migrations, models
from django.utils.text import slugify


def populate_profile_slugs(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    for profile in Profile.objects.select_related("user").filter(slug__isnull=True):
        full_name = f"{profile.user.first_name} {profile.user.last_name}".strip()
        base = slugify(profile.public_name or full_name or profile.user.email.split("@", 1)[0])
        profile.slug = f"{base or 'profissional'}-{uuid4().hex[:8]}"
        profile.save(update_fields=("slug",))


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_accepted_privacy_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=190, null=True, unique=True, verbose_name='slug público'),
        ),
        migrations.RunPython(populate_profile_slugs, migrations.RunPython.noop),
    ]
