# Generated by Django 5.2.16 on 2026-07-19 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovado em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='nota de revisão'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revisto em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL, verbose_name='revisto por'),
        ),
    ]
