# Generated by Django 5.2.16 on 2026-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_approved_at_profile_review_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_visibility',
            field=models.CharField(choices=[('form', 'Apenas formulário'), ('registered', 'Utilizadores registados'), ('public', 'Público'), ('hidden', 'Oculto')], default='form', max_length=20, verbose_name='visibilidade dos contactos'),
        ),
    ]
