# Generated by Django 5.2.16 on 2026-07-19 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_contact_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='versão pública em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='published_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='versão pública'),
        ),
        migrations.CreateModel(
            name='ProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='profiles.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_revisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_profile_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revisão de perfil',
                'verbose_name_plural': 'revisões de perfil',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
    ]
