# Generated by Django 5.2.16 on 2026-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_published_at_profile_published_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_visibility',
            field=models.CharField(choices=[('public', 'Público'), ('members', 'Utilizadores registados'), ('request', 'Apenas mediante pedido'), ('private', 'Privado')], default='private', max_length=20, verbose_name='visibilidade do currículo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_is_public',
            field=models.BooleanField(default=True, verbose_name='mostrar localização'),
        ),
    ]
