# Generated by Django 5.2.16 on 2026-07-26 14:01

from django.db import migrations, models


def copy_publication_state(apps, schema_editor):
    profile = apps.get_model("profiles", "Profile")
    profile.objects.filter(
        status__in=("approved", "changes_pending"),
        is_public=True,
    ).update(
        review_status="approved",
        is_discoverable=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_backfill_profile_search_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_discoverable',
            field=models.BooleanField(db_index=True, default=False, verbose_name='visível na rede'),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto para revisão'), ('under_review', 'Em revisão'), ('corrections_required', 'Correcções necessárias'), ('approved', 'Publicado')], db_index=True, default='draft', max_length=24, verbose_name='estado da publicação'),
        ),
        migrations.RunPython(copy_publication_state, migrations.RunPython.noop),
    ]
