# Generated by Django 5.2.16 on 2026-07-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_profile_contact_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180, verbose_name='assunto')),
                ('message', models.TextField(max_length=3000, verbose_name='mensagem')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregue'), ('blocked', 'Bloqueado'), ('reported', 'Denunciado')], db_index=True, default='sent', max_length=20)),
                ('sender_ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de contacto',
                'verbose_name_plural': 'pedidos de contacto',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=60, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('body', models.TextField(blank=True, max_length=1000, verbose_name='conteúdo')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='destino')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'profile'), name='unique_favorite')],
            },
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gosto',
                'verbose_name_plural': 'gostos',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'profile'), name='unique_profile_like')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('false_data', 'Informação falsa'), ('fraud', 'Suspeita de fraude'), ('impersonation', 'Dados de outra pessoa'), ('prohibited', 'Conteúdo proibido'), ('spam', 'Conteúdo promocional ou spam'), ('other', 'Outro motivo')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('reviewing', 'Em análise'), ('resolved', 'Resolvida'), ('dismissed', 'Arquivada')], db_index=True, default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='profiles.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'denúncia',
                'verbose_name_plural': 'denúncias',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'reviewing'))), fields=('reporter', 'profile'), name='unique_active_profile_report')],
            },
        ),
    ]
