# Generated by Django 5.2.16 on 2026-07-20 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='notes',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('saved', 'Guardado'), ('to_contact', 'Para contactar'), ('contacted', 'Contactado'), ('interview', 'Entrevista'), ('offer', 'Proposta'), ('hired', 'Contratado'), ('archived', 'Arquivado')], db_index=True, default='saved', max_length=24),
        ),
        migrations.AddField(
            model_name='favorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RecruitmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(editable=False, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'etiqueta de recrutamento',
                'verbose_name_plural': 'etiquetas de recrutamento',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='interactions.recruitmenttag'),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('query_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pesquisa guardada',
                'verbose_name_plural': 'pesquisas guardadas',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='recruitmenttag',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_name'), name='unique_recruitment_tag'),
        ),
    ]
