# Generated by Django 5.2.16 on 2026-07-26 14:12

from django.db import migrations, models


def normalize_contact_status(apps, schema_editor):
    contact_request = apps.get_model("interactions", "ContactRequest")
    contact_request.objects.filter(status__in=("sent", "delivered")).update(
        status="pending"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_recruitment_workspace'),
    ]

    operations = [
        migrations.RunPython(normalize_contact_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceite'), ('declined', 'Recusado'), ('blocked', 'Bloqueado'), ('reported', 'Denunciado')], db_index=True, default='pending', max_length=20),
        ),
    ]
