# Generated by Django 5.2.16 on 2026-07-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='taxonomy.sector', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specializations', to='taxonomy.area', verbose_name='área')),
            ],
            options={
                'verbose_name': 'especialização',
                'verbose_name_plural': 'especializações',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('specializations', models.ManyToManyField(blank=True, related_name='skills', to='taxonomy.specialization', verbose_name='especializações')),
            ],
            options={
                'verbose_name': 'competência',
                'verbose_name_plural': 'competências',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
