# Generated by Django 5.2.16 on 2026-07-26 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(blank=True, choices=[('effective', 'Efectivo'), ('observer', 'Observador')], max_length=16)),
                ('relationship', models.CharField(blank=True, choices=[('citizen', 'Cidadão da Guiné-Bissau'), ('diaspora', 'Descendente da diáspora'), ('relevant_link', 'Ligação relevante')], max_length=20)),
                ('relationship_note', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetida'), ('under_review', 'Em análise'), ('corrections_required', 'Correcções necessárias'), ('approved', 'Aprovada'), ('refused', 'Recusada'), ('suspended', 'Suspensa')], default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='MembershipDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetida'), ('under_review', 'Em análise'), ('corrections_required', 'Correcções necessárias'), ('approved', 'Aprovada'), ('refused', 'Recusada'), ('suspended', 'Suspensa')], max_length=24)),
                ('to_status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetida'), ('under_review', 'Em análise'), ('corrections_required', 'Correcções necessárias'), ('approved', 'Aprovada'), ('refused', 'Recusada'), ('suspended', 'Suspensa')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_decisions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='memberships.membership')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
