# Generated by Django 5.2.16 on 2026-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='accepts_code_of_conduct',
            field=models.BooleanField(default=False, verbose_name='Aceita o código de conduta'),
        ),
        migrations.AddField(
            model_name='membership',
            name='accepts_privacy',
            field=models.BooleanField(default=False, verbose_name='Aceita a política de privacidade'),
        ),
        migrations.AddField(
            model_name='membership',
            name='confirms_truth',
            field=models.BooleanField(default=False, verbose_name='Confirma a veracidade da candidatura'),
        ),
    ]
