# Generated by Django 5.2.16 on 2026-07-19 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='ação')),
                ('target_type', models.CharField(db_index=True, max_length=100, verbose_name='tipo de alvo')),
                ('target_id', models.CharField(db_index=True, max_length=64, verbose_name='identificador do alvo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'registo de auditoria',
                'verbose_name_plural': 'registos de auditoria',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
